# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd ../
        git clone https://github.com/resess/DynamicSlicingCore
        pwd
        cd DynamicSlicingCore/core
        mvn -DskipTests -B package install --file pom.xml
        cd ../../Slicer4J/Slicer4J 
        mvn -DskipTests -B package install --file pom.xml
        zip -rq Slicer4J.zip ./ 
        curl --upload-file ./Slicer4J.zip https://transfer.sh/Slicer4J.zip
        cd -
        cd ..
        zip  -rq DynamicSlicingCore.zip ./DynamicSlicingCore    
        curl --upload-file ./DynamicSlicingCore.zip https://transfer.sh/DynamicSlicingCore.zip
        
